### PR TITLE
Test

### PR DESCRIPTION
**Pull request by Azaryan1**

### CODE REVIEW

**Comment by vpez** [comment]
So, what is different from the previous MR? I see most of the same files changed.

**Comment by vpez** [comment]
Dear @Azaryan1 I meant compared to the MR https://github.com/AUA-CS322/aua-cs322-team-a-server/pull/2 opened by @MagaZargaryan, feels like both contain a big chunk of overlapping code(?)

**Comment by Azaryan1** [comment]
> Dear @Azaryan1 I meant compared to the MR #2 opened by @MagaZargaryan, feels like both contain a big chunk of overlapping code(?)

Dear @vpez I've made the Test branch, merged it with the Develop branch and then started writing the unit tests. Then I added two new folders to the Test folder which contained one file each. I'm guessing I should've not merged the Test and Develop branches ?

**Comment by vpez** [comment]
@Azaryan1 Yes, that's correct. It is advised to merge changes incrementally. If an existing feature branch is not merged into master, if you follow the steps you described, there is possibility that you merge more than what was intended. Let's wait until Develop is merged and then get back to this MR. After Develop is merged, you'll need to make this branch up to date with master and then we should be good to go.

**Pull request closed without merging**
